services:
  nginx:
    build: .
    container_name: nginx-https-app
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
